### ISSUE TITLE
main.py运行报错 SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by hyLiu1994** [Neboer/ipgw-py-manager#2]
我在如下python3.5 2.7都进行了测试结果如下
![image](https://user-images.githubusercontent.com/17963050/59896345-c663ca80-941a-11e9-9428-f63abdb3e330.png)

**Comment by Neboer** [comment]
这个是类型声明。类型声明似乎是Python3.7的特性，为了简化开发过程，我插入了许多这种类型声明，希望你用python3.7再试一次。
[typings python3.7](https://docs.python.org/3/library/typing.html)

**Comment by Neboer** [comment]
如果没有其他问题，这个issue关闭。
关于python版本，已在README里做出申明。

**Comment by Neboer** [comment]
如果没有其他问题，这个issue关闭。
关于python版本，已在README里做出申明。
